# Generated by Django 2.2.5 on 2023-05-30 20:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_num', models.IntegerField(max_length=10)),
                ('email_addr', models.CharField(max_length=30)),
                ('linkedin_id', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=30)),
            ],
            managers=[
                ('Users', django.db.models.manager.Manager()),
            ],
        ),
    ]
