# Generated by Django 2.2.5 on 2023-05-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedInScraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=15),
        ),
    ]
