# Generated by Django 2.2.5 on 2023-06-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedInScraper', '0002_auto_20230530_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
