# Generated by Django 2.2.5 on 2023-06-06 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('LinkedInScraper', '0003_auto_20230603_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LinkedInScraper.User')),
            ],
            managers=[
                ('FavoritedUsers', django.db.models.manager.Manager()),
            ],
        ),
    ]
